build_in: build
type: img
name: kasm.proxy.img
clear_build_path: true
next:
- build: docker
	build_in: docker
	copy:
	- ../srv: srv/
	config:
		base_image: kasmweb/nginx:latest
		image_name: eons/kasm.proxy.img
		image_os: debian
		also:		- COPY srv /srv
		tags:
		- "1.15.0"
		- latest
		entrypoint: /start.sh
- build: docker_publish
	run_when_any:
	- release
	build_in: publish
	config:
		image_name: eons/kasm.proxy.img
